
spring:
  application:
    name: cake-manager
  jpa:
    show-sql: true
    generated-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect


server:
  port: 8085